version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - apt-get update -y
      - apt-get install docker.io -y
      - sudo systemctl start docker
